In [1]:
usd = [10, 20, 30]
thb = []
for p in usd:
    thb.append(p * 33)
thb



[330, 660, 990]

In [2]:
import numpy as np


In [3]:
usd = np.array([10, 20, 30])
thb = usd * 33  # broadcasting # 10 * 33, 20 * 33, 30  33
thb

# scalar
# vector


array([330, 660, 990])

In [4]:
rate = np.array([33, 33, 33])
usd * rate


array([330, 660, 990])

In [5]:
c = np.array([2, 3, 4, 5, 6, 7, 8, 9])
r = np.arange(1, 13)



In [6]:
r


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
x = np.arange(1, 13).reshape(-1, 1)
y = np.arange(2, 10).reshape(1, -1)
# x*y
print(x)
print(y)
x*y

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[2 3 4 5 6 7 8 9]]


array([[  2,   3,   4,   5,   6,   7,   8,   9],
       [  4,   6,   8,  10,  12,  14,  16,  18],
       [  6,   9,  12,  15,  18,  21,  24,  27],
       [  8,  12,  16,  20,  24,  28,  32,  36],
       [ 10,  15,  20,  25,  30,  35,  40,  45],
       [ 12,  18,  24,  30,  36,  42,  48,  54],
       [ 14,  21,  28,  35,  42,  49,  56,  63],
       [ 16,  24,  32,  40,  48,  56,  64,  72],
       [ 18,  27,  36,  45,  54,  63,  72,  81],
       [ 20,  30,  40,  50,  60,  70,  80,  90],
       [ 22,  33,  44,  55,  66,  77,  88,  99],
       [ 24,  36,  48,  60,  72,  84,  96, 108]])

In [8]:
x = np.arange(1, 13)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
np.tile(x.reshape(12, 1), 8)



array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12]])

In [10]:
y


array([[2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
np.arange(2, 10).reshape(1, -1)



array([[2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
np.arange(1, 13).reshape(-1, 2)



array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
import numpy as np


def mult_table():
    ver = np.arange(2, 10)
    hor = np.arange(1, 13)
    return ver * hor[:, None]


print(mult_table())


[[  2   3   4   5   6   7   8   9]
 [  4   6   8  10  12  14  16  18]
 [  6   9  12  15  18  21  24  27]
 [  8  12  16  20  24  28  32  36]
 [ 10  15  20  25  30  35  40  45]
 [ 12  18  24  30  36  42  48  54]
 [ 14  21  28  35  42  49  56  63]
 [ 16  24  32  40  48  56  64  72]
 [ 18  27  36  45  54  63  72  81]
 [ 20  30  40  50  60  70  80  90]
 [ 22  33  44  55  66  77  88  99]
 [ 24  36  48  60  72  84  96 108]]


In [14]:
np.random.seed(501)


In [15]:
np.random.randint(1, 1001, 50)  # dice



array([ 88, 672, 680, 592, 481,  78, 735, 852, 694, 965, 503, 600, 417,
       435, 944, 153, 322, 733, 961,  66, 578, 178, 859, 302, 827, 740,
       316, 163, 824, 127, 457, 309, 815, 532, 148, 690, 778,  58, 232,
       369, 637, 383, 615, 400, 158, 734, 778, 302, 845, 657])

In [16]:
np.random.randint(1, 7, 10)


array([1, 6, 2, 6, 6, 3, 6, 6, 5, 6])

In [17]:
np.random.randint(1, 7, 10)


array([5, 1, 4, 3, 6, 1, 4, 3, 3, 6])

In [18]:
np.random.randint(1, 7, 10)


array([5, 4, 1, 2, 1, 6, 5, 6, 3, 1])